# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1185, 683)
        MainWindow.setMinimumSize(QtCore.QSize(0, 200))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setGeometry(QtCore.QRect(320, 0, 861, 441))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 844, 3464))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.trackwindow_layout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.trackwindow_layout.setObjectName("trackwindow_layout")
        self.trackui1 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.trackui1.setEnabled(False)
        self.trackui1.setMinimumSize(QtCore.QSize(0, 200))
        self.trackui1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.trackui1.setAutoFillBackground(False)
        self.trackui1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trackui1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trackui1.setObjectName("trackui1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.trackui1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.trackpanel1 = QtWidgets.QWidget(self.trackui1)
        self.trackpanel1.setMinimumSize(QtCore.QSize(180, 0))
        self.trackpanel1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.trackpanel1.setObjectName("trackpanel1")
        self.gridLayout = QtWidgets.QGridLayout(self.trackpanel1)
        self.gridLayout.setObjectName("gridLayout")
        self.track1_checkbox = QtWidgets.QCheckBox(self.trackpanel1)
        self.track1_checkbox.setObjectName("track1_checkbox")
        self.gridLayout.addWidget(self.track1_checkbox, 2, 0, 1, 1)
        self.Eliminar_track1 = QtWidgets.QPushButton(self.trackpanel1)
        self.Eliminar_track1.setObjectName("Eliminar_track1")
        self.gridLayout.addWidget(self.Eliminar_track1, 3, 0, 1, 2)
        self.Reproducir_track1 = QtWidgets.QPushButton(self.trackpanel1)
        self.Reproducir_track1.setObjectName("Reproducir_track1")
        self.gridLayout.addWidget(self.Reproducir_track1, 1, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.trackpanel1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.horizontalLayout.addWidget(self.trackpanel1)
        self.tracktimeline1 = MplWidget(self.trackui1)
        self.tracktimeline1.setMinimumSize(QtCore.QSize(500, 0))
        self.tracktimeline1.setObjectName("tracktimeline1")
        self.horizontalLayout.addWidget(self.tracktimeline1)
        self.trackwindow_layout.addWidget(self.trackui1)
        self.trackui2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.trackui2.setEnabled(False)
        self.trackui2.setMinimumSize(QtCore.QSize(0, 200))
        self.trackui2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trackui2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trackui2.setObjectName("trackui2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.trackui2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.trackpanel2 = QtWidgets.QWidget(self.trackui2)
        self.trackpanel2.setMinimumSize(QtCore.QSize(180, 0))
        self.trackpanel2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.trackpanel2.setObjectName("trackpanel2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.trackpanel2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Eliminar_track2 = QtWidgets.QPushButton(self.trackpanel2)
        self.Eliminar_track2.setObjectName("Eliminar_track2")
        self.gridLayout_4.addWidget(self.Eliminar_track2, 3, 0, 1, 1)
        self.Reproducir_track2 = QtWidgets.QPushButton(self.trackpanel2)
        self.Reproducir_track2.setObjectName("Reproducir_track2")
        self.gridLayout_4.addWidget(self.Reproducir_track2, 1, 0, 1, 1)
        self.track2_checkbox = QtWidgets.QCheckBox(self.trackpanel2)
        self.track2_checkbox.setObjectName("track2_checkbox")
        self.gridLayout_4.addWidget(self.track2_checkbox, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.trackpanel2)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.trackpanel2)
        self.tracktimeline2 = MplWidget(self.trackui2)
        self.tracktimeline2.setMinimumSize(QtCore.QSize(500, 0))
        self.tracktimeline2.setObjectName("tracktimeline2")
        self.horizontalLayout_2.addWidget(self.tracktimeline2)
        self.trackwindow_layout.addWidget(self.trackui2)
        self.trackui3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.trackui3.setEnabled(False)
        self.trackui3.setMinimumSize(QtCore.QSize(0, 200))
        self.trackui3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trackui3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trackui3.setObjectName("trackui3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.trackui3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.trackpanel3 = QtWidgets.QWidget(self.trackui3)
        self.trackpanel3.setMinimumSize(QtCore.QSize(180, 0))
        self.trackpanel3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.trackpanel3.setObjectName("trackpanel3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.trackpanel3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Reproducir_track3 = QtWidgets.QPushButton(self.trackpanel3)
        self.Reproducir_track3.setObjectName("Reproducir_track3")
        self.gridLayout_5.addWidget(self.Reproducir_track3, 1, 0, 1, 1)
        self.track3_checkbox = QtWidgets.QCheckBox(self.trackpanel3)
        self.track3_checkbox.setObjectName("track3_checkbox")
        self.gridLayout_5.addWidget(self.track3_checkbox, 2, 0, 1, 1)
        self.Eliminar_track3 = QtWidgets.QPushButton(self.trackpanel3)
        self.Eliminar_track3.setObjectName("Eliminar_track3")
        self.gridLayout_5.addWidget(self.Eliminar_track3, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.trackpanel3)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.trackpanel3)
        self.tracktimeline3 = MplWidget(self.trackui3)
        self.tracktimeline3.setMinimumSize(QtCore.QSize(500, 0))
        self.tracktimeline3.setObjectName("tracktimeline3")
        self.horizontalLayout_3.addWidget(self.tracktimeline3)
        self.trackwindow_layout.addWidget(self.trackui3)
        self.trackui4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.trackui4.setEnabled(False)
        self.trackui4.setMinimumSize(QtCore.QSize(0, 200))
        self.trackui4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trackui4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trackui4.setObjectName("trackui4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.trackui4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.trackpanel4 = QtWidgets.QWidget(self.trackui4)
        self.trackpanel4.setMinimumSize(QtCore.QSize(180, 0))
        self.trackpanel4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.trackpanel4.setObjectName("trackpanel4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.trackpanel4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_8 = QtWidgets.QLabel(self.trackpanel4)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 0, 0, 1, 1)
        self.Reproducir_track4 = QtWidgets.QPushButton(self.trackpanel4)
        self.Reproducir_track4.setObjectName("Reproducir_track4")
        self.gridLayout_6.addWidget(self.Reproducir_track4, 1, 0, 1, 1)
        self.Eliminar_track4 = QtWidgets.QPushButton(self.trackpanel4)
        self.Eliminar_track4.setObjectName("Eliminar_track4")
        self.gridLayout_6.addWidget(self.Eliminar_track4, 3, 0, 1, 1)
        self.track4_checkbox = QtWidgets.QCheckBox(self.trackpanel4)
        self.track4_checkbox.setObjectName("track4_checkbox")
        self.gridLayout_6.addWidget(self.track4_checkbox, 2, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.trackpanel4)
        self.tracktimeline4 = MplWidget(self.trackui4)
        self.tracktimeline4.setMinimumSize(QtCore.QSize(500, 0))
        self.tracktimeline4.setObjectName("tracktimeline4")
        self.horizontalLayout_4.addWidget(self.tracktimeline4)
        self.trackwindow_layout.addWidget(self.trackui4)
        self.trackui5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.trackui5.setEnabled(False)
        self.trackui5.setMinimumSize(QtCore.QSize(0, 200))
        self.trackui5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trackui5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trackui5.setObjectName("trackui5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.trackui5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.trackpanel5 = QtWidgets.QWidget(self.trackui5)
        self.trackpanel5.setMinimumSize(QtCore.QSize(180, 0))
        self.trackpanel5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.trackpanel5.setObjectName("trackpanel5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.trackpanel5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_9 = QtWidgets.QLabel(self.trackpanel5)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 0, 0, 1, 1)
        self.track5_checkbox = QtWidgets.QCheckBox(self.trackpanel5)
        self.track5_checkbox.setObjectName("track5_checkbox")
        self.gridLayout_7.addWidget(self.track5_checkbox, 2, 0, 1, 1)
        self.Eliminar_track5 = QtWidgets.QPushButton(self.trackpanel5)
        self.Eliminar_track5.setObjectName("Eliminar_track5")
        self.gridLayout_7.addWidget(self.Eliminar_track5, 3, 0, 1, 1)
        self.Reproducir_track5 = QtWidgets.QPushButton(self.trackpanel5)
        self.Reproducir_track5.setObjectName("Reproducir_track5")
        self.gridLayout_7.addWidget(self.Reproducir_track5, 1, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.trackpanel5)
        self.tracktimeline5 = MplWidget(self.trackui5)
        self.tracktimeline5.setMinimumSize(QtCore.QSize(500, 0))
        self.tracktimeline5.setObjectName("tracktimeline5")
        self.horizontalLayout_5.addWidget(self.tracktimeline5)
        self.trackwindow_layout.addWidget(self.trackui5)
        self.trackui6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.trackui6.setEnabled(False)
        self.trackui6.setMinimumSize(QtCore.QSize(0, 200))
        self.trackui6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trackui6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trackui6.setObjectName("trackui6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.trackui6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.trackpanel6 = QtWidgets.QWidget(self.trackui6)
        self.trackpanel6.setMinimumSize(QtCore.QSize(180, 0))
        self.trackpanel6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.trackpanel6.setObjectName("trackpanel6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.trackpanel6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.Reproducir_track6 = QtWidgets.QPushButton(self.trackpanel6)
        self.Reproducir_track6.setObjectName("Reproducir_track6")
        self.gridLayout_8.addWidget(self.Reproducir_track6, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.trackpanel6)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 0, 0, 1, 1)
        self.Eliminar_track6 = QtWidgets.QPushButton(self.trackpanel6)
        self.Eliminar_track6.setObjectName("Eliminar_track6")
        self.gridLayout_8.addWidget(self.Eliminar_track6, 3, 0, 1, 1)
        self.track6_checkbox = QtWidgets.QCheckBox(self.trackpanel6)
        self.track6_checkbox.setObjectName("track6_checkbox")
        self.gridLayout_8.addWidget(self.track6_checkbox, 2, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.trackpanel6)
        self.tracktimeline6 = MplWidget(self.trackui6)
        self.tracktimeline6.setMinimumSize(QtCore.QSize(500, 0))
        self.tracktimeline6.setObjectName("tracktimeline6")
        self.horizontalLayout_6.addWidget(self.tracktimeline6)
        self.trackwindow_layout.addWidget(self.trackui6)
        self.trackui7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.trackui7.setEnabled(False)
        self.trackui7.setMinimumSize(QtCore.QSize(0, 200))
        self.trackui7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trackui7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trackui7.setObjectName("trackui7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.trackui7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.trackpanel7 = QtWidgets.QWidget(self.trackui7)
        self.trackpanel7.setMinimumSize(QtCore.QSize(180, 0))
        self.trackpanel7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.trackpanel7.setObjectName("trackpanel7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.trackpanel7)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.track7_checkbox = QtWidgets.QCheckBox(self.trackpanel7)
        self.track7_checkbox.setObjectName("track7_checkbox")
        self.gridLayout_9.addWidget(self.track7_checkbox, 2, 0, 1, 1)
        self.Eliminar_track7 = QtWidgets.QPushButton(self.trackpanel7)
        self.Eliminar_track7.setObjectName("Eliminar_track7")
        self.gridLayout_9.addWidget(self.Eliminar_track7, 3, 0, 1, 1)
        self.Reproducir_track7 = QtWidgets.QPushButton(self.trackpanel7)
        self.Reproducir_track7.setObjectName("Reproducir_track7")
        self.gridLayout_9.addWidget(self.Reproducir_track7, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.trackpanel7)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.trackpanel7)
        self.tracktimeline7 = MplWidget(self.trackui7)
        self.tracktimeline7.setMinimumSize(QtCore.QSize(500, 0))
        self.tracktimeline7.setObjectName("tracktimeline7")
        self.horizontalLayout_7.addWidget(self.tracktimeline7)
        self.trackwindow_layout.addWidget(self.trackui7)
        self.trackui8 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.trackui8.setEnabled(False)
        self.trackui8.setMinimumSize(QtCore.QSize(0, 200))
        self.trackui8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trackui8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trackui8.setObjectName("trackui8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.trackui8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.trackpanel8 = QtWidgets.QWidget(self.trackui8)
        self.trackpanel8.setMinimumSize(QtCore.QSize(180, 0))
        self.trackpanel8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.trackpanel8.setObjectName("trackpanel8")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.trackpanel8)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.track8_checkbox = QtWidgets.QCheckBox(self.trackpanel8)
        self.track8_checkbox.setObjectName("track8_checkbox")
        self.gridLayout_10.addWidget(self.track8_checkbox, 2, 0, 1, 1)
        self.Eliminar_track8 = QtWidgets.QPushButton(self.trackpanel8)
        self.Eliminar_track8.setObjectName("Eliminar_track8")
        self.gridLayout_10.addWidget(self.Eliminar_track8, 3, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.trackpanel8)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_10.addWidget(self.label_12, 0, 0, 1, 1)
        self.Reproducir_track8 = QtWidgets.QPushButton(self.trackpanel8)
        self.Reproducir_track8.setObjectName("Reproducir_track8")
        self.gridLayout_10.addWidget(self.Reproducir_track8, 1, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.trackpanel8)
        self.tracktimeline8 = MplWidget(self.trackui8)
        self.tracktimeline8.setMinimumSize(QtCore.QSize(500, 0))
        self.tracktimeline8.setObjectName("tracktimeline8")
        self.horizontalLayout_8.addWidget(self.tracktimeline8)
        self.trackwindow_layout.addWidget(self.trackui8)
        self.trackui9 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.trackui9.setEnabled(False)
        self.trackui9.setMinimumSize(QtCore.QSize(0, 200))
        self.trackui9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trackui9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trackui9.setObjectName("trackui9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.trackui9)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.trackpanel9 = QtWidgets.QWidget(self.trackui9)
        self.trackpanel9.setMinimumSize(QtCore.QSize(180, 0))
        self.trackpanel9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.trackpanel9.setObjectName("trackpanel9")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.trackpanel9)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.Eliminar_track9 = QtWidgets.QPushButton(self.trackpanel9)
        self.Eliminar_track9.setObjectName("Eliminar_track9")
        self.gridLayout_11.addWidget(self.Eliminar_track9, 3, 0, 1, 1)
        self.track9_checkbox = QtWidgets.QCheckBox(self.trackpanel9)
        self.track9_checkbox.setObjectName("track9_checkbox")
        self.gridLayout_11.addWidget(self.track9_checkbox, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.trackpanel9)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_11.addWidget(self.label_13, 0, 0, 1, 1)
        self.Reproducir_track9 = QtWidgets.QPushButton(self.trackpanel9)
        self.Reproducir_track9.setObjectName("Reproducir_track9")
        self.gridLayout_11.addWidget(self.Reproducir_track9, 1, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.trackpanel9)
        self.tracktimeline9 = MplWidget(self.trackui9)
        self.tracktimeline9.setMinimumSize(QtCore.QSize(500, 0))
        self.tracktimeline9.setObjectName("tracktimeline9")
        self.horizontalLayout_9.addWidget(self.tracktimeline9)
        self.trackwindow_layout.addWidget(self.trackui9)
        self.trackui10 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.trackui10.setEnabled(False)
        self.trackui10.setMinimumSize(QtCore.QSize(0, 200))
        self.trackui10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trackui10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trackui10.setObjectName("trackui10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.trackui10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.trackpanel10 = QtWidgets.QWidget(self.trackui10)
        self.trackpanel10.setMinimumSize(QtCore.QSize(180, 0))
        self.trackpanel10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.trackpanel10.setObjectName("trackpanel10")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.trackpanel10)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_14 = QtWidgets.QLabel(self.trackpanel10)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_12.addWidget(self.label_14, 0, 0, 1, 1)
        self.Reproducir_track10 = QtWidgets.QPushButton(self.trackpanel10)
        self.Reproducir_track10.setObjectName("Reproducir_track10")
        self.gridLayout_12.addWidget(self.Reproducir_track10, 1, 0, 1, 1)
        self.track10_checkbox = QtWidgets.QCheckBox(self.trackpanel10)
        self.track10_checkbox.setObjectName("track10_checkbox")
        self.gridLayout_12.addWidget(self.track10_checkbox, 2, 0, 1, 1)
        self.Eliminar_track10 = QtWidgets.QPushButton(self.trackpanel10)
        self.Eliminar_track10.setObjectName("Eliminar_track10")
        self.gridLayout_12.addWidget(self.Eliminar_track10, 3, 0, 1, 1)
        self.horizontalLayout_10.addWidget(self.trackpanel10)
        self.tracktimeline10 = MplWidget(self.trackui10)
        self.tracktimeline10.setMinimumSize(QtCore.QSize(500, 0))
        self.tracktimeline10.setObjectName("tracktimeline10")
        self.horizontalLayout_10.addWidget(self.tracktimeline10)
        self.trackwindow_layout.addWidget(self.trackui10)
        self.trackui11 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.trackui11.setEnabled(False)
        self.trackui11.setMinimumSize(QtCore.QSize(0, 200))
        self.trackui11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trackui11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trackui11.setObjectName("trackui11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.trackui11)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.trackpanel11 = QtWidgets.QWidget(self.trackui11)
        self.trackpanel11.setMinimumSize(QtCore.QSize(180, 0))
        self.trackpanel11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.trackpanel11.setObjectName("trackpanel11")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.trackpanel11)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.Reproducir_track11 = QtWidgets.QPushButton(self.trackpanel11)
        self.Reproducir_track11.setObjectName("Reproducir_track11")
        self.gridLayout_13.addWidget(self.Reproducir_track11, 1, 0, 1, 1)
        self.track11_checkbox = QtWidgets.QCheckBox(self.trackpanel11)
        self.track11_checkbox.setObjectName("track11_checkbox")
        self.gridLayout_13.addWidget(self.track11_checkbox, 2, 0, 1, 1)
        self.Eliminar_track11 = QtWidgets.QPushButton(self.trackpanel11)
        self.Eliminar_track11.setObjectName("Eliminar_track11")
        self.gridLayout_13.addWidget(self.Eliminar_track11, 3, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.trackpanel11)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_13.addWidget(self.label_15, 0, 0, 1, 1)
        self.horizontalLayout_11.addWidget(self.trackpanel11)
        self.tracktimeline11 = MplWidget(self.trackui11)
        self.tracktimeline11.setMinimumSize(QtCore.QSize(500, 0))
        self.tracktimeline11.setObjectName("tracktimeline11")
        self.horizontalLayout_11.addWidget(self.tracktimeline11)
        self.trackwindow_layout.addWidget(self.trackui11)
        self.trackui12 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.trackui12.setEnabled(False)
        self.trackui12.setMinimumSize(QtCore.QSize(0, 200))
        self.trackui12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trackui12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trackui12.setObjectName("trackui12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.trackui12)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.trackpanel12 = QtWidgets.QWidget(self.trackui12)
        self.trackpanel12.setMinimumSize(QtCore.QSize(180, 0))
        self.trackpanel12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.trackpanel12.setObjectName("trackpanel12")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.trackpanel12)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.track12_checkbox = QtWidgets.QCheckBox(self.trackpanel12)
        self.track12_checkbox.setObjectName("track12_checkbox")
        self.gridLayout_14.addWidget(self.track12_checkbox, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.trackpanel12)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_14.addWidget(self.label_16, 0, 0, 1, 1)
        self.Reproducir_track12 = QtWidgets.QPushButton(self.trackpanel12)
        self.Reproducir_track12.setObjectName("Reproducir_track12")
        self.gridLayout_14.addWidget(self.Reproducir_track12, 1, 0, 1, 1)
        self.Eliminar_track12 = QtWidgets.QPushButton(self.trackpanel12)
        self.Eliminar_track12.setObjectName("Eliminar_track12")
        self.gridLayout_14.addWidget(self.Eliminar_track12, 3, 0, 1, 1)
        self.horizontalLayout_12.addWidget(self.trackpanel12)
        self.tracktimeline12 = MplWidget(self.trackui12)
        self.tracktimeline12.setMinimumSize(QtCore.QSize(500, 0))
        self.tracktimeline12.setObjectName("tracktimeline12")
        self.horizontalLayout_12.addWidget(self.tracktimeline12)
        self.trackwindow_layout.addWidget(self.trackui12)
        self.trackui13 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.trackui13.setEnabled(False)
        self.trackui13.setMinimumSize(QtCore.QSize(0, 200))
        self.trackui13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trackui13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trackui13.setObjectName("trackui13")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.trackui13)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.trackpanel13 = QtWidgets.QWidget(self.trackui13)
        self.trackpanel13.setMinimumSize(QtCore.QSize(180, 0))
        self.trackpanel13.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.trackpanel13.setObjectName("trackpanel13")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.trackpanel13)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.Reproducir_track13 = QtWidgets.QPushButton(self.trackpanel13)
        self.Reproducir_track13.setObjectName("Reproducir_track13")
        self.gridLayout_15.addWidget(self.Reproducir_track13, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.trackpanel13)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_15.addWidget(self.label_17, 0, 0, 1, 1)
        self.Eliminar_track13 = QtWidgets.QPushButton(self.trackpanel13)
        self.Eliminar_track13.setObjectName("Eliminar_track13")
        self.gridLayout_15.addWidget(self.Eliminar_track13, 3, 0, 1, 1)
        self.track13_checkbox = QtWidgets.QCheckBox(self.trackpanel13)
        self.track13_checkbox.setObjectName("track13_checkbox")
        self.gridLayout_15.addWidget(self.track13_checkbox, 2, 0, 1, 1)
        self.horizontalLayout_13.addWidget(self.trackpanel13)
        self.tracktimeline13 = MplWidget(self.trackui13)
        self.tracktimeline13.setMinimumSize(QtCore.QSize(500, 0))
        self.tracktimeline13.setObjectName("tracktimeline13")
        self.horizontalLayout_13.addWidget(self.tracktimeline13)
        self.trackwindow_layout.addWidget(self.trackui13)
        self.trackui14 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.trackui14.setEnabled(False)
        self.trackui14.setMinimumSize(QtCore.QSize(0, 200))
        self.trackui14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trackui14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trackui14.setObjectName("trackui14")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.trackui14)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.trackpanel14 = QtWidgets.QWidget(self.trackui14)
        self.trackpanel14.setMinimumSize(QtCore.QSize(180, 0))
        self.trackpanel14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.trackpanel14.setObjectName("trackpanel14")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.trackpanel14)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_18 = QtWidgets.QLabel(self.trackpanel14)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_16.addWidget(self.label_18, 0, 0, 1, 1)
        self.Eliminar_track14 = QtWidgets.QPushButton(self.trackpanel14)
        self.Eliminar_track14.setObjectName("Eliminar_track14")
        self.gridLayout_16.addWidget(self.Eliminar_track14, 3, 0, 1, 1)
        self.Reproducir_track14 = QtWidgets.QPushButton(self.trackpanel14)
        self.Reproducir_track14.setObjectName("Reproducir_track14")
        self.gridLayout_16.addWidget(self.Reproducir_track14, 1, 0, 1, 1)
        self.track14_checkbox = QtWidgets.QCheckBox(self.trackpanel14)
        self.track14_checkbox.setObjectName("track14_checkbox")
        self.gridLayout_16.addWidget(self.track14_checkbox, 2, 0, 1, 1)
        self.horizontalLayout_14.addWidget(self.trackpanel14)
        self.tracktimeline14 = MplWidget(self.trackui14)
        self.tracktimeline14.setMinimumSize(QtCore.QSize(500, 0))
        self.tracktimeline14.setObjectName("tracktimeline14")
        self.horizontalLayout_14.addWidget(self.tracktimeline14)
        self.trackwindow_layout.addWidget(self.trackui14)
        self.trackui15 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.trackui15.setEnabled(False)
        self.trackui15.setMinimumSize(QtCore.QSize(0, 200))
        self.trackui15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trackui15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trackui15.setObjectName("trackui15")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.trackui15)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.trackpanel15 = QtWidgets.QWidget(self.trackui15)
        self.trackpanel15.setMinimumSize(QtCore.QSize(180, 0))
        self.trackpanel15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.trackpanel15.setObjectName("trackpanel15")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.trackpanel15)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.track15_checkbox = QtWidgets.QCheckBox(self.trackpanel15)
        self.track15_checkbox.setObjectName("track15_checkbox")
        self.gridLayout_17.addWidget(self.track15_checkbox, 2, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.trackpanel15)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_17.addWidget(self.label_19, 0, 0, 1, 1)
        self.Eliminar_track15 = QtWidgets.QPushButton(self.trackpanel15)
        self.Eliminar_track15.setObjectName("Eliminar_track15")
        self.gridLayout_17.addWidget(self.Eliminar_track15, 3, 0, 1, 1)
        self.Reproducir_track15 = QtWidgets.QPushButton(self.trackpanel15)
        self.Reproducir_track15.setObjectName("Reproducir_track15")
        self.gridLayout_17.addWidget(self.Reproducir_track15, 1, 0, 1, 1)
        self.horizontalLayout_15.addWidget(self.trackpanel15)
        self.tracktimeline15 = MplWidget(self.trackui15)
        self.tracktimeline15.setMinimumSize(QtCore.QSize(500, 0))
        self.tracktimeline15.setObjectName("tracktimeline15")
        self.horizontalLayout_15.addWidget(self.tracktimeline15)
        self.trackwindow_layout.addWidget(self.trackui15)
        self.trackui16 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.trackui16.setEnabled(False)
        self.trackui16.setMinimumSize(QtCore.QSize(0, 200))
        self.trackui16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trackui16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trackui16.setObjectName("trackui16")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.trackui16)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.trackpanel16 = QtWidgets.QWidget(self.trackui16)
        self.trackpanel16.setMinimumSize(QtCore.QSize(180, 0))
        self.trackpanel16.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.trackpanel16.setObjectName("trackpanel16")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.trackpanel16)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_20 = QtWidgets.QLabel(self.trackpanel16)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_18.addWidget(self.label_20, 0, 0, 1, 1)
        self.track16_checkbox = QtWidgets.QCheckBox(self.trackpanel16)
        self.track16_checkbox.setObjectName("track16_checkbox")
        self.gridLayout_18.addWidget(self.track16_checkbox, 2, 0, 1, 1)
        self.Eliminar_track16 = QtWidgets.QPushButton(self.trackpanel16)
        self.Eliminar_track16.setObjectName("Eliminar_track16")
        self.gridLayout_18.addWidget(self.Eliminar_track16, 3, 0, 1, 1)
        self.Reproducir_track16 = QtWidgets.QPushButton(self.trackpanel16)
        self.Reproducir_track16.setObjectName("Reproducir_track16")
        self.gridLayout_18.addWidget(self.Reproducir_track16, 1, 0, 1, 1)
        self.horizontalLayout_16.addWidget(self.trackpanel16)
        self.tracktimeline16 = MplWidget(self.trackui16)
        self.tracktimeline16.setMinimumSize(QtCore.QSize(500, 0))
        self.tracktimeline16.setObjectName("tracktimeline16")
        self.horizontalLayout_16.addWidget(self.tracktimeline16)
        self.trackwindow_layout.addWidget(self.trackui16)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.Selector = QtWidgets.QFrame(self.centralwidget)
        self.Selector.setGeometry(QtCore.QRect(10, 42, 301, 231))
        self.Selector.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Selector.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Selector.setObjectName("Selector")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Selector)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.add_track = QtWidgets.QPushButton(self.Selector)
        self.add_track.setObjectName("add_track")
        self.gridLayout_2.addWidget(self.add_track, 3, 1, 1, 1)
        self.instrument_selector = QtWidgets.QComboBox(self.Selector)
        self.instrument_selector.setObjectName("instrument_selector")
        self.instrument_selector.addItem("")
        self.instrument_selector.addItem("")
        self.instrument_selector.addItem("")
        self.instrument_selector.addItem("")
        self.gridLayout_2.addWidget(self.instrument_selector, 3, 0, 1, 1)
        self.track_number = QtWidgets.QLabel(self.Selector)
        self.track_number.setMaximumSize(QtCore.QSize(16777215, 30))
        self.track_number.setObjectName("track_number")
        self.gridLayout_2.addWidget(self.track_number, 0, 0, 1, 2)
        self.label_21 = QtWidgets.QLabel(self.Selector)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 1, 0, 1, 1)
        self.track_selector = QtWidgets.QComboBox(self.Selector)
        self.track_selector.setObjectName("track_selector")
        self.gridLayout_2.addWidget(self.track_selector, 1, 1, 1, 1)
        self.reset = QtWidgets.QPushButton(self.Selector)
        self.reset.setObjectName("reset")
        self.gridLayout_2.addWidget(self.reset, 4, 0, 1, 2)
        self.synthesis_selector = QtWidgets.QComboBox(self.Selector)
        self.synthesis_selector.setObjectName("synthesis_selector")
        self.synthesis_selector.addItem("")
        self.synthesis_selector.addItem("")
        self.synthesis_selector.addItem("")
        self.gridLayout_2.addWidget(self.synthesis_selector, 2, 0, 1, 2)
        self.cargar_archivo = QtWidgets.QPushButton(self.centralwidget)
        self.cargar_archivo.setGeometry(QtCore.QRect(10, 10, 301, 31))
        self.cargar_archivo.setObjectName("cargar_archivo")
        self.Reproductor = QtWidgets.QFrame(self.centralwidget)
        self.Reproductor.setGeometry(QtCore.QRect(830, 490, 351, 141))
        self.Reproductor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Reproductor.setObjectName("Reproductor")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Reproductor)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.duration_lineedit = QtWidgets.QLineEdit(self.Reproductor)
        self.duration_lineedit.setText("")
        self.duration_lineedit.setObjectName("duration_lineedit")
        self.gridLayout_3.addWidget(self.duration_lineedit, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.Reproductor)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.instrument_selector_single_note = QtWidgets.QComboBox(self.Reproductor)
        self.instrument_selector_single_note.setObjectName("instrument_selector_single_note")
        self.instrument_selector_single_note.addItem("")
        self.instrument_selector_single_note.addItem("")
        self.instrument_selector_single_note.addItem("")
        self.instrument_selector_single_note.addItem("")
        self.gridLayout_3.addWidget(self.instrument_selector_single_note, 3, 2, 1, 1)
        self.single_note_selector = QtWidgets.QComboBox(self.Reproductor)
        self.single_note_selector.setObjectName("single_note_selector")
        self.single_note_selector.addItem("")
        self.single_note_selector.addItem("")
        self.single_note_selector.addItem("")
        self.single_note_selector.addItem("")
        self.single_note_selector.addItem("")
        self.single_note_selector.addItem("")
        self.single_note_selector.addItem("")
        self.gridLayout_3.addWidget(self.single_note_selector, 0, 2, 1, 1)
        self.synth_selector_single_note = QtWidgets.QComboBox(self.Reproductor)
        self.synth_selector_single_note.setObjectName("synth_selector_single_note")
        self.synth_selector_single_note.addItem("")
        self.synth_selector_single_note.addItem("")
        self.synth_selector_single_note.addItem("")
        self.gridLayout_3.addWidget(self.synth_selector_single_note, 2, 2, 1, 1)
        self.reproduce_single_note = QtWidgets.QPushButton(self.Reproductor)
        self.reproduce_single_note.setObjectName("reproduce_single_note")
        self.gridLayout_3.addWidget(self.reproduce_single_note, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.Reproductor)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.Reproductor)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.Reproductor)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.espectrograma = MplWidget(self.centralwidget)
        self.espectrograma.setGeometry(QtCore.QRect(0, 330, 341, 331))
        self.espectrograma.setObjectName("espectrograma")
        self.guardar_archivo = QtWidgets.QPushButton(self.centralwidget)
        self.guardar_archivo.setGeometry(QtCore.QRect(1040, 447, 141, 31))
        self.guardar_archivo.setObjectName("guardar_archivo")
        self.Reproducir_todo = QtWidgets.QPushButton(self.centralwidget)
        self.Reproducir_todo.setGeometry(QtCore.QRect(40, 280, 241, 41))
        self.Reproducir_todo.setObjectName("Reproducir_todo")
        self.save_name = QtWidgets.QLineEdit(self.centralwidget)
        self.save_name.setGeometry(QtCore.QRect(910, 454, 121, 21))
        self.save_name.setObjectName("save_name")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(774, 455, 121, 20))
        self.label_22.setObjectName("label_22")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(500, 490, 321, 141))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.espectrograma_track = QtWidgets.QPushButton(self.frame)
        self.espectrograma_track.setObjectName("espectrograma_track")
        self.gridLayout_19.addWidget(self.espectrograma_track, 3, 0, 1, 3)
        self.ventana_espectrograma = QtWidgets.QComboBox(self.frame)
        self.ventana_espectrograma.setObjectName("ventana_espectrograma")
        self.ventana_espectrograma.addItem("")
        self.ventana_espectrograma.addItem("")
        self.ventana_espectrograma.addItem("")
        self.ventana_espectrograma.addItem("")
        self.ventana_espectrograma.addItem("")
        self.ventana_espectrograma.addItem("")
        self.ventana_espectrograma.addItem("")
        self.ventana_espectrograma.addItem("")
        self.ventana_espectrograma.addItem("")
        self.ventana_espectrograma.addItem("")
        self.ventana_espectrograma.addItem("")
        self.ventana_espectrograma.addItem("")
        self.gridLayout_19.addWidget(self.ventana_espectrograma, 0, 1, 1, 2)
        self.label_23 = QtWidgets.QLabel(self.frame)
        self.label_23.setObjectName("label_23")
        self.gridLayout_19.addWidget(self.label_23, 0, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.frame)
        self.label_24.setObjectName("label_24")
        self.gridLayout_19.addWidget(self.label_24, 1, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.frame)
        self.label_25.setObjectName("label_25")
        self.gridLayout_19.addWidget(self.label_25, 2, 0, 1, 1)
        self.window_size = QtWidgets.QLineEdit(self.frame)
        self.window_size.setObjectName("window_size")
        self.gridLayout_19.addWidget(self.window_size, 1, 1, 1, 1)
        self.overlaping = QtWidgets.QLineEdit(self.frame)
        self.overlaping.setObjectName("overlaping")
        self.gridLayout_19.addWidget(self.overlaping, 2, 1, 1, 1)
        self.ventana_espectrograma.raise_()
        self.espectrograma_track.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.window_size.raise_()
        self.overlaping.raise_()
        self.label_23.raise_()
        self.panel_efectos = QtWidgets.QFrame(self.centralwidget)
        self.panel_efectos.setGeometry(QtCore.QRect(320, 450, 171, 181))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.panel_efectos.setFont(font)
        self.panel_efectos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.panel_efectos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.panel_efectos.setObjectName("panel_efectos")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.panel_efectos)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.speed = QtWidgets.QLabel(self.panel_efectos)
        self.speed.setObjectName("speed")
        self.gridLayout_20.addWidget(self.speed, 2, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.panel_efectos)
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_26.setFont(font)
        self.label_26.setScaledContents(False)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setWordWrap(True)
        self.label_26.setObjectName("label_26")
        self.gridLayout_20.addWidget(self.label_26, 0, 0, 1, 2)
        self.depth_lineedit = QtWidgets.QLineEdit(self.panel_efectos)
        self.depth_lineedit.setObjectName("depth_lineedit")
        self.gridLayout_20.addWidget(self.depth_lineedit, 3, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.panel_efectos)
        self.label_28.setObjectName("label_28")
        self.gridLayout_20.addWidget(self.label_28, 3, 0, 1, 1)
        self.speed_lineedit = QtWidgets.QLineEdit(self.panel_efectos)
        self.speed_lineedit.setObjectName("speed_lineedit")
        self.gridLayout_20.addWidget(self.speed_lineedit, 2, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.panel_efectos)
        self.label_29.setObjectName("label_29")
        self.gridLayout_20.addWidget(self.label_29, 4, 0, 1, 1)
        self.select_effect = QtWidgets.QComboBox(self.panel_efectos)
        self.select_effect.setObjectName("select_effect")
        self.select_effect.addItem("")
        self.select_effect.addItem("")
        self.gridLayout_20.addWidget(self.select_effect, 1, 0, 1, 2)
        self.efecto_reproducir = QtWidgets.QPushButton(self.panel_efectos)
        self.efecto_reproducir.setObjectName("efecto_reproducir")
        self.gridLayout_20.addWidget(self.efecto_reproducir, 5, 0, 1, 2)
        self.inversion = QtWidgets.QCheckBox(self.panel_efectos)
        self.inversion.setText("")
        self.inversion.setObjectName("inversion")
        self.gridLayout_20.addWidget(self.inversion, 4, 1, 1, 1)
        self.Selector.raise_()
        self.cargar_archivo.raise_()
        self.Reproductor.raise_()
        self.espectrograma.raise_()
        self.guardar_archivo.raise_()
        self.Reproducir_todo.raise_()
        self.save_name.raise_()
        self.label_22.raise_()
        self.frame.raise_()
        self.scrollArea.raise_()
        self.panel_efectos.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1185, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.track1_checkbox.setText(_translate("MainWindow", "Seleccionar Track"))
        self.Eliminar_track1.setText(_translate("MainWindow", "Eliminar track"))
        self.Reproducir_track1.setText(_translate("MainWindow", "Reproducir Track"))
        self.label.setText(_translate("MainWindow", "Track 1"))
        self.Eliminar_track2.setText(_translate("MainWindow", "Eliminar track"))
        self.Reproducir_track2.setText(_translate("MainWindow", "Reproducir Track"))
        self.track2_checkbox.setText(_translate("MainWindow", "Seleccionar Track"))
        self.label_6.setText(_translate("MainWindow", "Track 2"))
        self.Reproducir_track3.setText(_translate("MainWindow", "Reproducir Track"))
        self.track3_checkbox.setText(_translate("MainWindow", "Seleccionar Track"))
        self.Eliminar_track3.setText(_translate("MainWindow", "Eliminar track"))
        self.label_7.setText(_translate("MainWindow", "Track 3"))
        self.label_8.setText(_translate("MainWindow", "Track 4"))
        self.Reproducir_track4.setText(_translate("MainWindow", "Reproducir Track"))
        self.Eliminar_track4.setText(_translate("MainWindow", "Eliminar track"))
        self.track4_checkbox.setText(_translate("MainWindow", "Seleccionar Track"))
        self.label_9.setText(_translate("MainWindow", "Track 5"))
        self.track5_checkbox.setText(_translate("MainWindow", "Seleccionar Track"))
        self.Eliminar_track5.setText(_translate("MainWindow", "Eliminar track"))
        self.Reproducir_track5.setText(_translate("MainWindow", "Reproducir Track"))
        self.Reproducir_track6.setText(_translate("MainWindow", "Reproducir Track"))
        self.label_10.setText(_translate("MainWindow", "Track 6"))
        self.Eliminar_track6.setText(_translate("MainWindow", "Eliminar track"))
        self.track6_checkbox.setText(_translate("MainWindow", "Seleccionar Track"))
        self.track7_checkbox.setText(_translate("MainWindow", "Seleccionar Track"))
        self.Eliminar_track7.setText(_translate("MainWindow", "Eliminar track"))
        self.Reproducir_track7.setText(_translate("MainWindow", "Reproducir Track"))
        self.label_11.setText(_translate("MainWindow", "Track 7"))
        self.track8_checkbox.setText(_translate("MainWindow", "Seleccionar Track"))
        self.Eliminar_track8.setText(_translate("MainWindow", "Eliminar track"))
        self.label_12.setText(_translate("MainWindow", "Track 8"))
        self.Reproducir_track8.setText(_translate("MainWindow", "Reproducir Track"))
        self.Eliminar_track9.setText(_translate("MainWindow", "Eliminar track"))
        self.track9_checkbox.setText(_translate("MainWindow", "Seleccionar Track"))
        self.label_13.setText(_translate("MainWindow", "Track 9"))
        self.Reproducir_track9.setText(_translate("MainWindow", "Reproducir Track"))
        self.label_14.setText(_translate("MainWindow", "Track 10"))
        self.Reproducir_track10.setText(_translate("MainWindow", "Reproducir Track"))
        self.track10_checkbox.setText(_translate("MainWindow", "Seleccionar Track"))
        self.Eliminar_track10.setText(_translate("MainWindow", "Eliminar track"))
        self.Reproducir_track11.setText(_translate("MainWindow", "Reproducir Track"))
        self.track11_checkbox.setText(_translate("MainWindow", "Seleccionar Track"))
        self.Eliminar_track11.setText(_translate("MainWindow", "Eliminar track"))
        self.label_15.setText(_translate("MainWindow", "Track 11"))
        self.track12_checkbox.setText(_translate("MainWindow", "Seleccionar Track"))
        self.label_16.setText(_translate("MainWindow", "Track 12"))
        self.Reproducir_track12.setText(_translate("MainWindow", "Reproducir Track"))
        self.Eliminar_track12.setText(_translate("MainWindow", "Eliminar track"))
        self.Reproducir_track13.setText(_translate("MainWindow", "Reproducir Track"))
        self.label_17.setText(_translate("MainWindow", "Track 13"))
        self.Eliminar_track13.setText(_translate("MainWindow", "Eliminar track"))
        self.track13_checkbox.setText(_translate("MainWindow", "Seleccionar Track"))
        self.label_18.setText(_translate("MainWindow", "Track 14"))
        self.Eliminar_track14.setText(_translate("MainWindow", "Eliminar track"))
        self.Reproducir_track14.setText(_translate("MainWindow", "Reproducir Track"))
        self.track14_checkbox.setText(_translate("MainWindow", "Seleccionar Track"))
        self.track15_checkbox.setText(_translate("MainWindow", "Seleccionar Track"))
        self.label_19.setText(_translate("MainWindow", "Track 15"))
        self.Eliminar_track15.setText(_translate("MainWindow", "Eliminar track"))
        self.Reproducir_track15.setText(_translate("MainWindow", "Reproducir Track"))
        self.label_20.setText(_translate("MainWindow", "Track 16"))
        self.track16_checkbox.setText(_translate("MainWindow", "Seleccionar Track"))
        self.Eliminar_track16.setText(_translate("MainWindow", "Eliminar track"))
        self.Reproducir_track16.setText(_translate("MainWindow", "Reproducir Track"))
        self.add_track.setText(_translate("MainWindow", "Agregar track"))
        self.instrument_selector.setItemText(0, _translate("MainWindow", "piano"))
        self.instrument_selector.setItemText(1, _translate("MainWindow", "flute"))
        self.instrument_selector.setItemText(2, _translate("MainWindow", "violin"))
        self.instrument_selector.setItemText(3, _translate("MainWindow", "trumpet"))
        self.track_number.setText(_translate("MainWindow", "Hay x Tracks en su archivo."))
        self.label_21.setText(_translate("MainWindow", "Seleccione un Track"))
        self.reset.setText(_translate("MainWindow", "Reset Tracks"))
        self.synthesis_selector.setItemText(0, _translate("MainWindow", "Sintesis aditiva"))
        self.synthesis_selector.setItemText(1, _translate("MainWindow", "Sintesis fisica"))
        self.synthesis_selector.setItemText(2, _translate("MainWindow", "Sintesis basada en muestras"))
        self.cargar_archivo.setText(_translate("MainWindow", "Cargar archivo"))
        self.label_3.setText(_translate("MainWindow", "Nota"))
        self.instrument_selector_single_note.setItemText(0, _translate("MainWindow", "piano"))
        self.instrument_selector_single_note.setItemText(1, _translate("MainWindow", "flute"))
        self.instrument_selector_single_note.setItemText(2, _translate("MainWindow", "violin"))
        self.instrument_selector_single_note.setItemText(3, _translate("MainWindow", "trumpet"))
        self.single_note_selector.setItemText(0, _translate("MainWindow", "Do"))
        self.single_note_selector.setItemText(1, _translate("MainWindow", "Re"))
        self.single_note_selector.setItemText(2, _translate("MainWindow", "Mi"))
        self.single_note_selector.setItemText(3, _translate("MainWindow", "Fa"))
        self.single_note_selector.setItemText(4, _translate("MainWindow", "Sol"))
        self.single_note_selector.setItemText(5, _translate("MainWindow", "La"))
        self.single_note_selector.setItemText(6, _translate("MainWindow", "Si"))
        self.synth_selector_single_note.setItemText(0, _translate("MainWindow", "Sintesis aditiva"))
        self.synth_selector_single_note.setItemText(1, _translate("MainWindow", "Sintesis por muestras"))
        self.synth_selector_single_note.setItemText(2, _translate("MainWindow", "Sintesis física"))
        self.reproduce_single_note.setText(_translate("MainWindow", "Reproducir"))
        self.label_5.setText(_translate("MainWindow", "Instrumento"))
        self.label_2.setText(_translate("MainWindow", "Duración de nota:"))
        self.label_4.setText(_translate("MainWindow", "Tipo de Sintesis:"))
        self.guardar_archivo.setText(_translate("MainWindow", "Guardar pista"))
        self.Reproducir_todo.setText(_translate("MainWindow", "Reproducir Tracks seleccionados"))
        self.label_22.setText(_translate("MainWindow", "Nombre del archivo:"))
        self.espectrograma_track.setText(_translate("MainWindow", "Espectrograma de tracks seleccionados"))
        self.ventana_espectrograma.setItemText(0, _translate("MainWindow", "boxcar"))
        self.ventana_espectrograma.setItemText(1, _translate("MainWindow", "triang"))
        self.ventana_espectrograma.setItemText(2, _translate("MainWindow", "blackman"))
        self.ventana_espectrograma.setItemText(3, _translate("MainWindow", "hamming"))
        self.ventana_espectrograma.setItemText(4, _translate("MainWindow", "hann"))
        self.ventana_espectrograma.setItemText(5, _translate("MainWindow", "bartlett"))
        self.ventana_espectrograma.setItemText(6, _translate("MainWindow", "flattop"))
        self.ventana_espectrograma.setItemText(7, _translate("MainWindow", "parzen"))
        self.ventana_espectrograma.setItemText(8, _translate("MainWindow", "bohman"))
        self.ventana_espectrograma.setItemText(9, _translate("MainWindow", "blackmanharris"))
        self.ventana_espectrograma.setItemText(10, _translate("MainWindow", "nuttall"))
        self.ventana_espectrograma.setItemText(11, _translate("MainWindow", "barthann"))
        self.label_23.setText(_translate("MainWindow", "Ventana"))
        self.label_24.setText(_translate("MainWindow", "Tamaño de ventana (samples)"))
        self.label_25.setText(_translate("MainWindow", "Overlaping (max 50%)"))
        self.speed.setText(_translate("MainWindow", "Speed (0 - 100)"))
        self.label_26.setText(_translate("MainWindow", "Efectos Tracks"))
        self.label_28.setText(_translate("MainWindow", "Depth (0 - 1)"))
        self.label_29.setText(_translate("MainWindow", "Inversion "))
        self.select_effect.setItemText(0, _translate("MainWindow", "Flanger"))
        self.select_effect.setItemText(1, _translate("MainWindow", "Chorus"))
        self.efecto_reproducir.setText(_translate("MainWindow", "Reproducir"))
from MplWidget import MplWidget
